version: '3'

services:
  mysql:
    container_name: mozipmozip-mysql
    image: mysql:5.7
    volumes:
      - ./infrastructure/container/mysql/my.cnf:/etc/mysql/my.cnf
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=mozipmozip
      - MYSQL_USER=local
      - MYSQL_PASSWORD=local
    ports:
      - 6606:3306
