spring:
  profiles:
    active: local
  flyway:
    enabled: false
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: validate
---
spring:
  profiles: local
  datasource:
    url: jdbc:mysql://localhost:6606/mozipmozip?autoReconnect=true&useSSL=false&useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
    username: local
    password: local
    initialization-mode: always
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
---
spring:
  profiles: prod
  datasource:
    url: jdbc:h2:mem:mozipmozip;MODE=MySQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
    driver-class-name: org.h2.Driver
    initialization-mode: always
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
