apiVersion: apps/v1
kind: Deployment
metadata:
  name: mozip-api
spec:
  template:
    spec:
      containers:
        - name: mozip-api
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 300
