apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - external-dns-service-account.yaml
  - external-dns-cluster-role.yaml
  - external-dns-cluster-role-binding.yaml
  - external-dns-deployment.yaml

vars:
  - name: DOMAIN_FILTER
    objref:
      kind: Deployment
      name: external-dns
      apiVersion: extensions/v1beta1
    fieldref:
      fieldpath: metadata.annotations.external-dns/domain-filter
